# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-02 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DillerCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OperationContractorCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OperationManufactoryCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OperationProjectCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOrder', models.CharField(blank=True, default=uuid.uuid4, max_length=36)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('nameOrder', models.CharField(max_length=255)),
                ('nameContract', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('trelloLink', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('cost', models.IntegerField(blank=True, default=0, null=True)),
                ('prepayment', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RequiredMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('idMaterial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.MaterialCatalog')),
                ('idOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.Order')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredOperationContractor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('isDone', models.BooleanField()),
                ('isDoneDate', models.DateField()),
                ('idOperation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.OperationContractorCatalog')),
                ('idOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.Order')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredOperationManufactory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('isDone', models.BooleanField()),
                ('isDoneDate', models.DateField()),
                ('idOperation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.OperationManufactoryCatalog')),
                ('idOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.Order')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredOperationProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('isDone', models.BooleanField()),
                ('isDoneDate', models.DateField()),
                ('idOperation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.OperationProjectCatalog')),
                ('idOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.Order')),
            ],
        ),
        migrations.CreateModel(
            name='StatusCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('orderliness', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('idMaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orloveFurniture.MaterialCatalog')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('position', models.ManyToManyField(to='orloveFurniture.PositionCatalog')),
            ],
        ),
        migrations.AddField(
            model_name='requiredoperationproject',
            name='idWorker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.WorkerCatalog'),
        ),
        migrations.AddField(
            model_name='requiredoperationmanufactory',
            name='idWorker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.WorkerCatalog'),
        ),
        migrations.AddField(
            model_name='requiredoperationcontractor',
            name='idWorker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.WorkerCatalog'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.StatusCatalog'),
        ),
    ]
