# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-12 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idOrder',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=36),
        ),
    ]
