# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-02 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='fio',
        ),
        migrations.RemoveField(
            model_name='order',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='order',
            name='surname',
        ),
    ]
