# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-12 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0002_auto_20200112_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiredmaterial',
            name='idOrder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orloveFurniture.Order'),
            preserve_default=False,
        ),
    ]
