# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-02 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0003_auto_20200202_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='workercatalog',
            name='idWorker',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=36),
        ),
    ]
