# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-08 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0004_workercatalog_idworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategoryCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTypeCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.MaterialCategoryCatalog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.MaterialTypeCatalog'),
            preserve_default=False,
        ),
    ]
