# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0005_auto_20200119_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='dillercatalog',
            name='phone',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
