# Generated by Django 3.0 on 2020-01-07 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0006_auto_20200106_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiredmaterial',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requiredmaterial',
            name='idOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orloveFurniture.Order'),
        ),
    ]
