# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-19 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0006_dillercatalog_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscatalog',
            name='orderliness',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
