# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-12 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0006_auto_20200412_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcategorycatalog',
            name='name_2',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
