# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-12 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0007_materialcategorycatalog_name_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialcategorycatalog',
            name='name_2',
        ),
    ]
