# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-19 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0007_statuscatalog_orderliness'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='prepayment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
