# Generated by Django 3.0 on 2020-01-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0007_auto_20200107_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiredmaterial',
            name='idMaterial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orloveFurniture.MaterialCatalog'),
        ),
    ]
