# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-25 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0010_auto_20200119_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredoperation',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='requiredoperation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requiredoperation',
            name='idOperation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orloveFurniture.OperationCatalog'),
        ),
        migrations.AlterField(
            model_name='requiredoperation',
            name='idOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orloveFurniture.Order'),
        ),
        migrations.AlterField(
            model_name='requiredoperation',
            name='idWorker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orloveFurniture.WorkerCatalog'),
        ),
    ]
