# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-25 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0012_auto_20200125_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiredoperation',
            name='idOperation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orloveFurniture.OperationCatalog'),
        ),
        migrations.AlterField(
            model_name='requiredoperation',
            name='idWorker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orloveFurniture.WorkerCatalog'),
        ),
    ]
