# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-25 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0013_auto_20200125_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiredoperation',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
