# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0014_auto_20200125_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiredmaterial',
            name='idMaterial',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orloveFurniture.MaterialCatalog'),
            preserve_default=False,
        ),
    ]
