# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-01 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orloveFurniture', '0016_auto_20200126_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nameContract',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='nameOrder',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='trelloLink',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.StatusCatalog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requiredmaterial',
            name='idMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.MaterialCatalog'),
        ),
        migrations.AlterField(
            model_name='requiredmaterial',
            name='idOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.Order'),
        ),
        migrations.AlterField(
            model_name='requiredoperation',
            name='idOperation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.OperationCatalog'),
        ),
        migrations.AlterField(
            model_name='requiredoperation',
            name='idOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.Order'),
        ),
        migrations.AlterField(
            model_name='requiredoperation',
            name='idWorker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orloveFurniture.WorkerCatalog'),
        ),
    ]
